# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  install:
    runs-on: ubuntu-latest 
    steps:
    
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Yarn setup 
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 20.x

      - name: Cypress install 
        uses: cypress-io/github-action@v6
        with:
          runTests: false 
          build: yarn build

      - name: Save build folder 
        uses: actions/upload-artifact@v4 
        with:
          name: dist
          if-no-files-found: error 
          path: dist 
  
  cypress-run:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Download the build folder 
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist 
          
      - name: Cypress run 
        uses: cypress-io/github-action@v6
        with:
          start: yarn start 
          browser: chrome

  deploy:
    runs-on: ubuntu-latest 
    permissions:
      contents: write 
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3 

      - name: Setup Node 
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' 

      - name: Cache dependencies 
        uses: actions/chache@v3 
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Yarn setup 
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          node-version: 20.x 

      - run: yarn build 
      - name: deploy 
        uses: peaceiris/actions-gh-pages@v4 
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{secrets.GITHUB_TOKEN }} 
          publish_dir: ./dist
